### ISSUE TITLE
Test Harness - MySQL Generate Table and Insert

### ISSUE THREAD

**Issue by stemount** [DGKSK8LIFE/redisql#33]
- Firstly, define `users` table
  - id (int & auto increment & Primary Key (PK))
  - name - not index
  - uuid (string) - index
  - height. ("5ft9" - string)
  - shoesize (number) must support Smol size - not a whole number (4.5)
  - age (integer)
  - bio (string)
  - friends_count (random between 3 - 75)
  - favourite_animal (string)
  - favourite_colour  (string)
  - favourite_food  (string)
  - mobile_phone (string)

**Technical A/C**
- One of the tests need to be write 1,000,000 insert queries into MySQL.
- Drop database completely before it does the test suite.

**Summary**
The purpose of this ticket is to prime an example MySQL db.

The intention is to write this inside the Go package so that eventually it can be in CI/CD.

Maybe use Faker for things like the favourite animal just to ensure that all sorts of string lengths and data is in the DB.

**Outcomes**
- This could be recycled for other test suites, e.g. running 10,000 records with the replication later.
- Ensure that the use of MySQL driver in the solution can handle this.
- Pick a suitable testing framework (that automatically just profiles the amount of time it does).

**Comment by DGKSK8LIFE** [comment]
HOLY SH!T! Wrote a jank test case and redisql handled it with ease. Going to spend the next few days refactoring it (as well as implementing it for all the other types), then will optimize under the hood accordingly. Let's get it.
